name: vms_client_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0'

fluwx:
  app_id: '123456'
  debug_logging: true # Logging in debug mode.
  android:
  #    interrupt_wx_request: true # Defaults to true.
  #    flutter_activity: 'MainActivity' # Defaults to app's launcher
  ios:
    universal_link: https://testdomain.com
#    scene_delegate: true # Defaults to false.
#    no_pay: false # Set to false to disable payment.

dependencies: 
  get: 4.6.5
  url_launcher: ^6.1.12
  bruno: ^3.4.1
  easy_refresh: ^3.3.2+1
  card_swiper: ^3.0.1
  fluwx: ^4.2.7
  flutter_smart_dialog: ^4.9.4
  flutter_screenutil: ^5.8.4
  waterfall_flow: ^3.0.2
  left_scroll_actions: ^2.1.2
  shared_preferences: ^2.2.0
  permission_handler: ^10.4.3
  logger: ^2.0.1
  intl: ^0.18.1
  pinput: ^3.0.0
  extended_image: ^8.1.0
  image_picker: ^1.0.2
  flutter_widget_from_html: ^0.10.3
#  flutter_qweather: ^0.0.11 和风天气插件
  dio:
    git:
      url: https://github.com/cfug/diox
      path: dio/
      ref: dio

  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/icons/mine/
    - assets/tabbar/
  uses-material-design: true

